admin_token: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=32') }}"
mysql_root_password: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=16') }}"
namespaces:
# Namespaces to be populated
  - bitwarden
  - blog
  # Add other namespaces as needed
kubernetes_secrets:
  - name: vaultwarden-admin-token
    namespace: bitwarden
    data:
      ADMIN_TOKEN: "{{ admin_token | b64encode }}"
  - name: mysql-secret
    namespace: blog
    data:
      MYSQL_ROOT_PASSWORD: "{{ mysql_root_password | b64encode }}"
