- name: Generate Kubernetes secrets with random keys
  block:
    - name: Check if secret exists
      k8s_info:
        api_version: v1
        kind: Secret
        namespace: "{{ item.namespace }}"
        name: "{{ item.name }}"
      register: secret_info
      loop: "{{ kubernetes_secrets }}"
      loop_control:
        loop_var: item
      environment:
        KUBECONFIG: "/var/snap/microk8s/current/credentials/client.config"
        PATH: "/snap/bin:{{ ansible_env.PATH }}"

    - name: Create Kubernetes secret
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: "{{ item.name }}"
            namespace: "{{ item.namespace }}"
          type: Opaque
          data: "{{ item.data }}"
      when: secret_info.results[loop.index0].resources | length == 0
      loop: "{{ kubernetes_secrets }}"
      loop_control:
        loop_var: item
      environment:
        KUBECONFIG: "/var/snap/microk8s/current/credentials/client.config"
        PATH: "/snap/bin:{{ ansible_env.PATH }}"
