- name: Check if secret exists
  k8s_info:
    api_version: v1
    kind: Secret
    namespace: "{{ item.namespace }}"
    name: "{{ item.name }}"
  register: secret_info
  loop: "{{ kubernetes_secrets }}"
  loop_control:
    loop_var: item
  environment:
    KUBECONFIG: "/var/snap/microk8s/current/credentials/client.config"
    PATH: "/snap/bin:{{ ansible_env.PATH }}"

- name: Create Kubernetes secret
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ item.item.name }}"
        namespace: "{{ item.item.namespace }}"
      type: Opaque
      data: "{{ item.item.data }}"
  when: item.resources | length == 0
  with_items: "{{ secret_info.results }}"
  loop_control:
    label: "{{ item.item.name }}"
  environment:
    KUBECONFIG: "/var/snap/microk8s/current/credentials/client.config"
    PATH: "/snap/bin:{{ ansible_env.PATH }}"

