- name: Install MicroK8s via snap
  snap:
    name: microk8s
    classic: yes
    state: present

- name: Wait for MicroK8s to be ready
  shell: microk8s status --wait-ready
  args:
    executable: /bin/bash
  environment:
    PATH: "/snap/bin:{{ ansible_env.PATH }}"

- name: Enable MicroK8s addons on master node
  shell: microk8s enable cert-manager helm3 hostpath-storage ingress observability rbac
  args:
    executable: /bin/bash
  environment:
    PATH: "/snap/bin:{{ ansible_env.PATH }}"
  when: "'master' in group_names"